### ISSUE TITLE
Sarah can't login/upload: screen shot below

### ISSUE THREAD

**Issue by justacks** [rotblauer/openbound#21]
![img_8544](https://cloud.githubusercontent.com/assets/10282200/26588456/02273fbc-451b-11e7-95ce-e68000cf536a.JPG)

**Comment by whilei** [comment]
Note: is `422 Unprocessable Entity`

**Comment by whilei** [comment]
```
2017-05-24 15:56:08 +0000: Rack app error handling request { POST /login.action }
#<ArgumentError: string contains null byte>
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/multipart/parser.rb:22:in `extname'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/multipart/parser.rb:22:in `block in create'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/multipart/parser.rb:135:in `call'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/multipart/parser.rb:135:in `get_current_head_and_filename_and_content_type_and_name_and_body'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/multipart/parser.rb:59:in `block in parse'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/multipart/parser.rb:56:in `loop'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/multipart/parser.rb:56:in `parse'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/multipart.rb:25:in `parse_multipart'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/request.rb:375:in `parse_multipart'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/request.rb:207:in `POST'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:39:in `method_override_param'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:27:in `method_override'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:15:in `call'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-cache-1.7.0/lib/rack/cache/context.rb:140:in `forward'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-cache-1.7.0/lib/rack/cache/context.rb:147:in `pass'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-cache-1.7.0/lib/rack/cache/context.rb:159:in `invalidate'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-cache-1.7.0/lib/rack/cache/context.rb:74:in `call!'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-cache-1.7.0/lib/rack/cache/context.rb:51:in `call'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/puma-3.7.1/lib/puma/configuration.rb:232:in `call'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/puma-3.7.1/lib/puma/server.rb:578:in `handle_request'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/puma-3.7.1/lib/puma/server.rb:415:in `process_client'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/puma-3.7.1/lib/puma/server.rb:275:in `block in run'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/puma-3.7.1/lib/puma/thread_pool.rb:120:in `call'
/home/deploy/apps/openbound/shared/bundle/ruby/2.2.0/gems/puma-3.7.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by whilei** [comment]
Related: https://bitbucket.org/ged/ruby-pg/issues/198/argumenterror-string-contains-null-byte

**Comment by whilei** [comment]
May be resolved with 5ea6601. @justacks Have Sarah try again plz?

**Comment by justacks** [comment]
She tried again – kept(still) rejecting her gmail email, so she used a different one and got in (I'm not sure which one). She can now see that she has two accounts, and is wondering how to delete/merge one of them.

**Comment by whilei** [comment]
I just manually migrated her first account (with projects, works, and comments) to her newest. I can delete the first one if she wants. She can also change her email if she wants, once the first one is deleted.
